### ISSUE TITLE
Cython has to be run manually

### ISSUE THREAD

**Issue by uycire** [klavinslab/coral#1] opened 2015-08-20 21:58 UTC
When installing pymbt, I get the following error:

```
error: can't copy 'pymbt/analysis/_sequencing/calign.c': doesn't exist or not a regular file
```

It goes away after I manually run

```
cythonize(['pymbt/analysis/_sequencing/calign.pyx'])
```

and restart the build.

I'm using Python 2.7 and Cython 0.23.

**Comment by nbolten** [comment] 2015-08-21 00:23
It works here on a vanilla ubuntu 14.04 image. I've included the generated calign.c file in case cython import fails for whatever reason. Let me know if the issue is fixed!

**Comment by nbolten** [comment] 2015-09-11 23:27
I've removed the Cython dependency (it's now optional), so a pure C version should now compile and is compiling on Travis-CI. I'm closing this issue for now, but will reopen if it's still causing problems.

**Closed as completed by nbolten** 2015-09-11 23:27 UTC
